name: flutter_group1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  video_player: ^2.9.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  video_player_platform_interface: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/taiyuan/
    - assets/images/beijing/
    - assets/images/linyi/
    - assets/videos/